server:
  port: 8989

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
